steps:
  - name: trolleksii/cloudbuilder-terraform
    entrypoint: /bin/sh
    args:
      - -c
      - |
        cd ./terraform
        terraform init -input=false -no-color
        terraform apply -auto-approve -input=false -no-color -var-file=main.tfvars
        APP_URL=$(terraform output -json status | jq -r ".[].url")
        curl -H 'Content-Type: application/json' -d "{\"text\": \"$APP_URL\"}" $_WEBHOOK_URL
