steps:
  - name: trolleksii/cloudbuilder-terraform
    entrypoint: /bin/sh
    args:
      - -c
      - |
        cd ./terraform
        terraform init -input=false -no-color
        terraform apply -auto-approve -input=false -no-color -var-file=prod.tfvars
        curl -H 'Content-Type: application/json' -d "{\"text\": \"TSuccessfull deployment to the [production environment]($(terraform output -json status | jq -r ".[].url"))\"}" $_WEBHOOK_URL
