steps:
  - name: trolleksii/cloudbuilder-terraform
    entrypoint: /bin/terraform
    args:
      - init
      - -input=false
      - -no-color
      - ./terraform
  - name: trolleksii/cloudbuilder-terraform
    entrypoint: /bin/terraform
    args:
      - apply
      - -auto-approve
      - -input=false
      - -no-color
      - -var-file=terraform/main.tfvars
      - ./terraform
