steps:
  - name: trolleksii/cloudbuilder-terraform
    args:
      - init
      - -input=false
      - -no-color
      - ./terraform
  - name: trolleksii/cloudbuilder-terraform
    args:
      - plan
      - -no-color
      - -input=false
      - -var-file=terraform/main.tfvars
      - ./terraform
