steps:
  - name: trolleksii/cloudbuilder-terraform
    entrypoint: /bin/sh
    args:
      - -c
      - |
        cd ./terraform
        terraform init -input=false -no-color
        terraform apply -auto-approve -input=false -no-color -var-file=main.tfvars
        terraform output -json status | jq -r ".[].url"
