steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/sh
    args:
      - -c
      - |
        gsutil ls gs://gitops-terraform-status
  - name: trolleksii/cloudbuilder-terraform
    args:
      - init
      - -input=false
      - -no-color
      - ./terraform
  - name: trolleksii/cloudbuilder-terraform
    args:
      - apply
      - -auto-approve
      - -input=false
      - -no-color
      - -var-file=terraform/main.tfvars
      - ./terraform
