steps:
  - name: alpine
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        terraform init -input=false -no-color ./terraform
        terraform plan -input=false -no-color -var-file=main.tfvars ./terraform
