steps:
  - name: trolleksii/terraform
    args:
      - init -no-color -input=false -var-file=terraform/main.tfvars terraform
  - name: trolleksii/terraform
    args:
      - plan -no-color -input=false -var-file=terraform/main.tfvars terraform
