steps:
  - name: trolleksii/cloudbuilder-terraform
    entrypoint: /bin/sh
    args:
      - -c
      - |
        cd ./terraform
        terraform init -input=false -no-color
        terraform apply -auto-approve -input=false -no-color -var-file=main.tfvars
        curl -sH 'Content-Type: application/json' -d "{\"text\": \"The preview environment is at: $(terraform output -json status | jq -r ".[].url")\"}" $_WEBHOOK_URL
        curl -sH 'Content-Type: application/json' -d "{\"text\": \"Create a PR to propagate to prod: https://github.com/trolleksii/gitops-demo-infra/compare/dev?expand=1\"}" $_WEBHOOK_URL
