steps:
  - name: trolleksii/cloudbuilder-terraform
    entrypoint: /bin/sh
    args:
      - -c
      - |
        terraform init -input=false -no-color ./terraform
        terraform apply -auto-approve -input=false -no-color -var-file=terraform/main.tfvars ./terraform
        terraform output -json status | jq -r ".[].url"